version: '3.8'

services:
  app:
    container_name: task_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: ["./gradlew", "bootRun", "--stacktrace"]
    networks:
        - app-network

  mysql:
    image: mysql:8.0
    container_name: task_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestionTareas
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
        - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8181:80"

volumes:
  mysql_data:
    driver: local
  app:
    driver: local
networks:
    app-network:
        driver: bridge


